global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'dormcare'
    static_configs:
      - targets: ['host.docker.internal:5191']
        labels:
          service: dormcare

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
***